version: 2

jobs:
  build_data:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - add_ssh_keys:
        fingerprints:
          - "40:fd:de:3f:0d:31:ae:56:68:40:77:86:53:37:ed:80"
      - checkout
      - run: bundle install
      - run: bundle exec ruby scripts/update_data.rb
      - run: bash scripts/create_pull_request_if_needed.sh

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_data


